### ISSUE TITLE
ERRORs:  Reference and Main panels are not well aligned        ;      Line=91660 found=5 fields, expected=11 or 12

### ISSUE THREAD

**Issue by greekkey** [dmiller903/CompoundHetVIP#2]
Hi, I am trying CompoundHetVIP with the example data. I encountered some errors in Step 6 (Phase each of the trios using SHAPEIT2). 

    One error information was given in the beginning: 
        Reading SNPs in [/references/1000GP_Phase3/1000GP_Phase3_chr1.legend.gz]
        * 263213 reference panel sites included
        * 6237145 reference panel sites excluded
         ERROR: Reference and Main panels are not well aligned:
        * #Missing sites in reference panel = 9627
        * #Misaligned sites between panels = 1702
        * #Multiple alignments between panels = 8
        * 
     The other error was given in the end: 
         Reading site list and haplotypes in [giab/giab_GRCh37_chr1_shapeit.haps]
         ERROR: Line=81169 found=9 fields, expected=11 or 12
     
      Just under the second error, an information showed the process was done. What are those errors mean? 
      Thank you very much in advance!
Jacob

**Comment by greekkey** [comment]
The whole log for chr1 is here: 

Segmented HAPlotype Estimation & Imputation Tool
  * Authors : Olivier Delaneau, Jared O'Connell, Jean-François Zagury, Jonathan Marchini
  * Contact : send an email to the OXSTATGEN mail list https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=OXSTATGEN
  * Webpage : https://mathgen.stats.ox.ac.uk/shapeit
  * Version : v2.r904
  * Date    : 23/12/2021 05:00:30
  * LOGfile : [giab/giab_GRCh37_chr1_shapeit_check.log]

MODE -summarise : GENERATING SUMMARY STATISTICS OF THE INPUT DATA
  * Autosome (chr1 ... chr22)
  * Reference panel of haplotypes used


Parameters :
  * Seed : 1640235630
  * Parallelisation: 3 threads
  * Ref allele is NOT aligned on the reference genome

Reading site list in [giab/giab_GRCh37_chr1.bim]
  * 274534 sites included

Reading sample list in [giab/giab_GRCh37_chr1.fam]
  * 3 samples included
  * 0 unrelateds / 0 duos / 1 trios in 1 different families

Reading genotypes in [giab/giab_GRCh37_chr1.bed]
  * Plink binary file SNP-major mode

Reading sample list [/references/1000GP_Phase3/1000GP_Phase3.sample]
  * 5008 reference haplotypes included

Reading SNPs in [/references/1000GP_Phase3/1000GP_Phase3_chr1.legend.gz]
  * 263213 reference panel sites included
  * 6237145 reference panel sites excluded

ERROR: Reference and Main panels are not well aligned:
  * #Missing sites in reference panel = 9627
  * #Misaligned sites between panels = 1702
  * #Multiple alignments between panels = 8

Segmented HAPlotype Estimation & Imputation Tool
  * Authors : Olivier Delaneau, Jared O'Connell, Jean-François Zagury, Jonathan Marchini
  * Contact : send an email to the OXSTATGEN mail list https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=OXSTATGEN
  * Webpage : https://mathgen.stats.ox.ac.uk/shapeit
  * Version : v2.r904
  * Date    : 23/12/2021 05:00:47
  * LOGfile : [giab/giab_GRCh37_chr1_shapeit.log]

MODE -phase : PHASING GENOTYPE DATA
  * Autosome (chr1 ... chr22)
  * Window-based model (SHAPEIT v2)
  * Reference panel of haplotypes used
  * MCMC iteration

Parameters :
  * Seed : 123456789
  * Parallelisation: 3 threads
  * Ref allele is NOT aligned on the reference genome
  * MCMC: 35 iterations [7 B + 1 runs of 8 P + 20 M]
  * Model: 100 states per window [100 H + 0 PM + 0 R + 0 COV ] / Windows of ~2.0 Mb / Ne = 15000

Reading SNPs to exclude from input file in [giab/giab_GRCh37_chr1_shapeit_check.snp.strand.exclude]
  * 12161 snps found in the exclude list

Reading site list in [giab/giab_GRCh37_chr1.bim]
  * 263197 sites included
  * 11337 sites excluded

Reading sample list in [giab/giab_GRCh37_chr1.fam]
  * 3 samples included
  * 0 unrelateds / 0 duos / 1 trios in 1 different families

Reading genotypes in [giab/giab_GRCh37_chr1.bed]
  * Plink binary file SNP-major mode

Reading sample list [/references/1000GP_Phase3/1000GP_Phase3.sample]
  * 5008 reference haplotypes included

Reading SNPs in [/references/1000GP_Phase3/1000GP_Phase3_chr1.legend.gz]
  * 263197 reference panel sites included
  * 6237161 reference panel sites excluded

Reading reference haplotypes in [/references/1000GP_Phase3/1000GP_Phase3_chr1.hap.gz]

Reading genetic map in [/references/1000GP_Phase3/genetic_map_chr1_combined_b37.txt]
  * 248796 genetic positions found
  * #set=98422 / #interpolated=164775
  * Physical map [0.75 Mb -> 249.21 Mb] / Genetic map [0.49 cM -> 293.39 cM]

Checking missingness and MAF...
  * 2 individuals with high rates of missing data (>5%)
  * 105021 SNPs with high rates of missing data (>5%)
  * 1158 monomorphic SNPs
  * 15 missing genotypes automatically imputed at monomorphic SNPs
  * 309 singletons SNPs

Checking Mendel errors...
  * Low level of Mendel error in all trios and duos
  * 2 SNPs with high Mendel error rate (> 5%)

Building graphs [1/1]
  * 1 graphs / 54905 segments / ~4 SNPs per segment / 12839360 transitions
  * 0 haploids / 0 unrelateds / 0 duos / 1 trios
  * 4 founder haplotypes
  * 5008 reference haplotypes

Sampling haplotypes [1/1]

Burn-in iteration [1/7] [1/1]

Burn-in iteration [2/7] [1/1]

Burn-in iteration [3/7] [1/1]

Burn-in iteration [4/7] [1/1]

Burn-in iteration [5/7] [1/1]

Burn-in iteration [6/7] [1/1]

Burn-in iteration [7/7] [1/1]

Pruning iteration [1/8] [1/1]

Pruning iteration [2/8] [1/1]

Pruning iteration [3/8] [1/1]

Pruning iteration [4/8] [1/1]

Pruning iteration [5/8] [1/1]

Pruning iteration [6/8] [1/1]

Pruning iteration [7/8] [1/1]

Pruning iteration [8/8] [1/1]

Pruning graphs [1/1]
  * 1 graphs / 10306 segments / ~25 SNPs per segment / 81186 transitions
  * 0 haploids / 0 unrelateds / 0 duos / 1 trios
  * 4 founder haplotypes
  * 5008 reference haplotypes

Main iteration [1/20] [1/1]

Main iteration [2/20] [1/1]

Main iteration [3/20] [1/1]

Main iteration [4/20] [1/1]

Main iteration [5/20] [1/1]

Main iteration [6/20] [1/1]

Main iteration [7/20] [1/1]

Main iteration [8/20] [1/1]

Main iteration [9/20] [1/1]

Main iteration [10/20] [1/1]

Main iteration [11/20] [1/1]

Main iteration [12/20] [1/1]

Main iteration [13/20] [1/1]

Main iteration [14/20] [1/1]

Main iteration [15/20] [1/1]

Main iteration [16/20] [1/1]

Main iteration [17/20] [1/1]

Main iteration [18/20] [1/1]

Main iteration [19/20] [1/1]

Main iteration [20/20] [1/1]

Normalising graphs [1/1]

Solving haplotypes [1/1]

Writing sample list in [giab/giab_GRCh37_chr1_shapeit.sample]

Writing site list and haplotypes in [giab/giab_GRCh37_chr1_shapeit.haps]

Running time: 2305 seconds

Segmented HAPlotype Estimation & Imputation Tool
  * Authors : Olivier Delaneau, Jared O'Connell, Jean-François Zagury, Jonathan Marchini
  * Contact : send an email to the OXSTATGEN mail list https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=OXSTATGEN
  * Webpage : https://mathgen.stats.ox.ac.uk/shapeit
  * Version : v2.r904
  * Date    : 23/12/2021 05:39:12
  * LOGfile : [giab/giab_GRCh37_chr1_shapeit_vcf.log]

MODE -convert : CONVERTING/SUBSETTING SHAPEIT HAPLOTYPES

Parameters :
  * Seed : 1640237952
  * Parallelisation: 1 threads
  * Ref allele is NOT aligned on the reference genome

Reading sample list in [giab/giab_GRCh37_chr1_shapeit.sample]
  * 3 individuals included

Reading site list and haplotypes in [giab/giab_GRCh37_chr1_shapeit.haps]

ERROR: Line=81169 found=9 fields, expected=11 or 12

**********************************************************************
Done. Time elapsed: 38.71 minutes (0.65 hours)
**********************************************************************

**Comment by greekkey** [comment]
The same errors were also seen in chr2

**Comment by greekkey** [comment]
/giab_GRCh37_chr1_shapeit.vcf is empty. 
Here are the files for chr1 
https://drive.google.com/drive/folders/13GVr5yHDAoHOwmvqHxHt8QWuN6EIuz9O?usp=sharing

**Comment by dmiller903** [comment]
Hello @greekkey,

SHAPEIT2 requires a Haplotype reference panel in order to phase when there are only a few samples. The program compares the sites in the input file to that of the reference files. I'll try to break down what each part is saying in bold:

Reading SNPs in [/references/1000GP_Phase3/1000GP_Phase3_chr1.legend.gz]
    * 263213 reference panel sites included - ****There are 263,213 sites in common between the reference panel and input file (file that needs to be phased)****
    * 6237145 reference panel sites excluded - ****There are 6,237,145 reference panel sites in that are not found in the input file, so it won't look at these sites****
     ERROR: Reference and Main panels are not well aligned:
    * #Missing sites in reference panel = 9627 - ****The input file has 9,627 sites that are not found in the reference panel, so the program doesn't know how to phase these sites because it doesn't have a reference to go off****
    * #Misaligned sites between panels = 1702 ****There are 1702 sites between the reference panel and input file that have some sort of issue (maybe the ref allele in the panel is G and the ref allele in the input file is C), so the program doesn't know how to handle it.****

So out of the positions in the input file ~96% will be phased because they can be found in the reference panel. ~4% will be excluded because they are not in the reference panel, or the allelic calls in the ref panel and input file do not agree with each other. So in short, there are positions that are going to be excluded from phasing due to incompatibility issues, unfortunately. This is something I can not fix due to current phasing limitations.

With regards to the other issue, I'm not able to replicate it on my end of things. I just re-ran the giab trio from step 1 and did not encounter an issues during step 6. If you look in the giab/giab_GRCh37_chr1_shapeit.haps file on line 81169, there are a bunch of "NUL" values. I've never seen this before. For some reason SHAPEIT2 is inputing NUL values, so when it tries to cover to VCF, it doesn't know what to do. I assume you used all steps of CompoundHetVIP (1-6)? Can you try running step 6 again for chr1? 

If you have the same issue after retrying, I could add some code that checks the .haps file for "NUL" values and removes them before SHAPEIT2 tries to convert it to VCF.

**Comment by greekkey** [comment]
Hi @dmiller903, 
    Thank you very much for the detailed answer! 
    **So the first error is actually not a real error, right?** 
    The relationship of the numbers is 
             274534 (variants in chr1.bim) = 263213 (variants included in the reference) + 9627 (variants missed in the reference) + 1702 (variants misaligned) - 8 (multi-aligned variants)
    Only the 263213 variants included in the reference should be considered in the following steps.  

As for the second error, I think it might be related to the permissions of the directory /1000GP_Phase3/. I set the reference directory in NAS and ran the program yesterday, and encountered the second error. Then I checked the permissions of the files in the directory /1000GP_Phase3/ (in NAS), it was -rwxr-xr-x. Since you specially mentioned "chmod -R 777" in the python script, I thought it might matter. So I moved the /reference/ directory to a local disk and confirmed that the permissions of the files in the /1000GP_Phase3/ (in local disk) was -rwxrwxrwx. I then ran step 6 again; the second error disappeared.
(**So step 6 / SHAPEIT2 do need to write something in the files downloaded to /1000GP_Phase3/, right?** )
Here are the new files for chr1.
https://drive.google.com/drive/folders/10zjoLAjO2flJtDN5MUwfA7MxdmRE9pKN?usp=sharing
The /giab_GRCh37_chr1_shapeit.vcf.gz file is 1.5 M. Could please check whether it is correct?

By the way, **the program can only check for autosomal chromosomes, right?** I saw the 1000GP_Phase3 files for X chromosome were divided into three. In page 6 of the /CompoundHetVIP_example.pdf, "for i in range(1, 23):" was printed, **I guess it is a typo, right?**

Thanks again!
Merry Christmas!
Jacob

**Comment by greekkey** [comment]
As for the second error, I think it might be related to the permissions of the directory /1000GP_Phase3/. I set the reference directory in NAS and ran the program yesterday, and encountered the second error. Then I checked the permissions of the files in the directory /1000GP_Phase3/ (in NAS), it was -rwxr-xr-x. Since you specially mentioned "chmod -R 777" in the python script, I thought it might matter. So I moved the /reference/ directory to a local disk and confirmed that the permissions of the files in the /1000GP_Phase3/ (in local disk) was -rwxrwxrwx. I then ran step 6 again; the second error disappeared. 
    (**So step 6 / SHAPEIT2 do need to write something in the files downloaded to /1000GP_Phase3/, right?** )
    Here are the new files for chr1. 
    https://drive.google.com/drive/folders/10zjoLAjO2flJtDN5MUwfA7MxdmRE9pKN?usp=sharing
    The /giab_GRCh37_chr1_shapeit.vcf.gz file is 1.5 M. Could please check whether it is correct?

**Comment by greekkey** [comment]
By the way, **the program can only check for autosomal chromosomes, right?** I saw the 1000GP_Phase3 files for X chromosome were divided into three. In page 6 of the /CompoundHetVIP_example.pdf, "for i in range(1, 23):" was printed, **I guess it is a typo, right?** 
    Thanks again! 
    Merry  Christmas!
Jacob

**Comment by dmiller903** [comment]
Glad you were able to figure it out. Permissions can be a real pain at times.

Correct, the first error is not actually an error, it's more informational. It looks like you are interpreting the information correctly. According to SHAPEIT's documentation, "Assuming you use 1,000 Genomes reference panel; these constraints should not be a major problem since most of the chip SNPs are expected to be found.". They use the word "most" which is subjective, but I'd say 96% of the input SNPs being found in the reference is "most". 

Yes, since CompoundHetVIP focuses on CH variants, we only include ability to phase autosomal chromosomes. On page 6, where I use "for i in range(1, 23):", that is not a typo. It's python code which does not include 23 in the range. It's saying 1 up-to (but not including) 23. So 1-22. 

Merry Christmas to you too!

**Comment by greekkey** [comment]
Thanks for replying so quickly! 
Yes, you are using python in which the start is included but the stop is not included. I got it! 
Best regards!
Jabob
